[package]
name = "kisp"
version = "0.1.0"
edition = "2021"
default-run = "repl"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "repl"
path = "src/bin/repl.rs"

[dependencies]
linefeed = "0.6"